// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TContent: typeof import('tdesign-vue-next')['Content']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
  }
}

export { }
